<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

<form name="formUser" action="" method="post">
       <div class="form-group">
    <label  for="exampleInputPassword1">ชื่อกิจกรรม</label>
    <input type="text" class="form-control" id="name" name="name" required="" value="">
  </div>
       
        <div class="form-group">
          <label for="exampleInputPassword1">Date: </label>
          <div class="col-sm-10">
            <input class="form-control" id="birth" name="birth" required=""  type="date">
          </div>
        </div>
        <div class="form-group">
    <label  for="exampleFormControlTextarea1">รายละเอียด</label>
    <textarea class="form-control" id="detail" name="detail" required=""  rows="3"></textarea>
  </div>
        <div class="input-group mb-3">
  <div class="input-group-prepend">
    <span class="input-group-text">Upload</span>
  </div>
  
  <div class="custom-file">
    <input type="file" class="custom-file-input" id="file" name="file">
    <label class="custom-file-label" for="inputGroupFile01">Choose file</label>
  </div>
</div>
      


        <div class="form-group">
          <input class="btn btn-sm btn-success" type="submit" value="Submit">
        </div>
      </form>
      </head>