<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <?php
$id=$this->session->get('id');
$event=Event::findFirst("id='$id'");
?>
  <form name="formUser" action="" method="post" enctype="multipart/form-data">
    <div class="form-group">
      <label for="exampleInputPassword1">ชื่อกิจกรรม</label>
      <input type="text" class="form-control" id="name" name="name" required="" value="<?php echo $event->name;?>">
    </div>

    <div class="form-group">
      <label for="exampleInputPassword1">Date: </label>
      <div class="col-sm-10">
        <input class="form-control" id="birth" name="birth" required="" value="<?php echo $event->date;?>" type="date">
      </div>
    </div>
    <div class="form-group">
      <label for="exampleFormControlTextarea1">รายละเอียด</label>
      <textarea class="form-control" id="detail" name="detail" required="" rows="3">
        <?php echo $event->detail;?>
      </textarea>
    </div>
    <div class="form-group custom-file">
      <input type="file" class="custom-file-input" id="file" name="file">
      <label class="custom-file-label" for="inputGroupFile01">Choose file</label>
    </div>
    <?php if($event->picture!=''){?>
    <div class="form-group text-center">
      <img style="width:150px; height:150px; padding: 20px;" src="<?php echo $this->url->getBaseUri().'public/img/'.$event->picture; ?>">
    </div>
    <?php }?>



    <div class="form-group text-right">
      <input class="btn btn-sm btn-success" type="submit" value="Submit">
    </div>
  </form>
</head>